import Foundation

enum L10n {
    static func string(_ key: String, language: AppLanguagePreference) -> String {
        let resolvedLanguage = resolvedLanguage(for: language)
        return tables[resolvedLanguage]?[key] ?? tables[.english]?[key] ?? key
    }

    static func format(_ key: String, language: AppLanguagePreference, _ arguments: CVarArg...) -> String {
        String(format: string(key, language: language), locale: language.locale, arguments: arguments)
    }

    private static func resolvedLanguage(for language: AppLanguagePreference) -> AppLanguagePreference {
        guard language == .macOS else { return language }

        let identifier = Locale.preferredLanguages.first ?? Locale.autoupdatingCurrent.identifier
        if identifier.hasPrefix("ru") {
            return .russian
        } else if identifier.hasPrefix("de") {
            return .german
        } else {
            return .english
        }
    }

    private static let tables: [AppLanguagePreference: [String: String]] = [
        .english: [
            "phase.focus": "Focus",
            "phase.break": "Break",
            "timer.pause": "Pause",
            "timer.start": "Start",
            "timer.reset": "Reset",
            "timer.track": "Track",
            "timer.skip": "Skip",
            "settings.intervals": "Intervals",
            "settings.focus": "Focus",
            "settings.break": "Break",
            "settings.none": "none",
            "settings.time.allMinutes": "All Minutes",
            "settings.time.withHours": "With Hours",
            "settings.language": "Language",
            "performance.title": "Performance",
            "performance.streak": "Streak %d d",
            "performance.today": "Today",
            "performance.sessions": "sessions",
            "performance.focus": "Focus",
            "performance.tracked": "Tracked",
            "history.day": "Day",
            "history.pomodoros": "Pomodoros",
            "history.active": "Active",
            "history.enableScroll": "Enable scroll",
            "history.disableScroll": "Disable scroll",
            "activities.title": "Activities",
            "activities.new": "New activity",
            "activities.empty": "No daily activities yet.",
            "activities.edit": "Edit",
            "activities.save": "Save",
            "activities.completed": "Completed",
            "activities.target": "Target",
            "activities.start": "Start",
            "activities.stop": "Stop",
            "activities.interval.short": "Int.",
            "footer.history": "History is saved locally.",
            "footer.quit": "Quit",
            "track.noApps": "No apps available",
            "track.stop": "Stop Tracking",
            "away.30s": "30 seconds",
            "away.2m": "2 minutes",
            "away.5m": "5 minutes",
            "away.15m": "15 minutes",
            "away.indefinite": "Indefinite",
            "alert.focus.title": "Current streak is over",
            "alert.focus.message": "Nice work. Start a new focus streak now or take your configured break.",
            "alert.focus.startNew": "Start New Streak",
            "alert.focus.startBreak": "Start Break",
            "alert.later": "Later",
            "alert.activity.progress": "Daily activity progress: %d/%d",
            "alert.activity.done": "Done",
            "alert.activity.stopReminding": "Stop Reminding"
        ],
        .russian: [
            "phase.focus": "Фокус",
            "phase.break": "Перерыв",
            "timer.pause": "Пауза",
            "timer.start": "Старт",
            "timer.reset": "Сброс",
            "timer.track": "Трек",
            "timer.skip": "Пропустить",
            "settings.intervals": "Интервалы",
            "settings.focus": "Фокус",
            "settings.break": "Перерыв",
            "settings.none": "нет",
            "settings.time.allMinutes": "Все в минутах",
            "settings.time.withHours": "С часами",
            "settings.language": "Язык",
            "performance.title": "Прогресс",
            "performance.streak": "Серия %d д",
            "performance.today": "Сегодня",
            "performance.sessions": "сессии",
            "performance.focus": "Фокус",
            "performance.tracked": "Трекинг",
            "history.day": "День",
            "history.pomodoros": "Помидоры",
            "history.active": "Активно",
            "history.enableScroll": "Включить прокрутку",
            "history.disableScroll": "Отключить прокрутку",
            "activities.title": "Активности",
            "activities.new": "Новая активность",
            "activities.empty": "Пока нет активностей.",
            "activities.edit": "Править",
            "activities.save": "Сохранить",
            "activities.completed": "Готово",
            "activities.target": "Цель",
            "activities.start": "Старт",
            "activities.stop": "Стоп",
            "activities.interval.short": "Инт.",
            "footer.history": "История сохранена локально.",
            "footer.quit": "Выход",
            "track.noApps": "Нет приложений",
            "track.stop": "Не отслеживать",
            "away.30s": "30 секунд",
            "away.2m": "2 минуты",
            "away.5m": "5 минут",
            "away.15m": "15 минут",
            "away.indefinite": "Бессрочно",
            "alert.focus.title": "Текущая серия закончена",
            "alert.focus.message": "Хорошая работа. Начните новую серию фокуса сейчас или сделайте настроенный перерыв.",
            "alert.focus.startNew": "Новая серия",
            "alert.focus.startBreak": "Начать перерыв",
            "alert.later": "Позже",
            "alert.activity.progress": "Прогресс активности: %d/%d",
            "alert.activity.done": "Готово",
            "alert.activity.stopReminding": "Не напоминать"
        ],
        .german: [
            "phase.focus": "Fokus",
            "phase.break": "Pause",
            "timer.pause": "Pausieren",
            "timer.start": "Start",
            "timer.reset": "Zurucksetzen",
            "timer.track": "Tracken",
            "timer.skip": "Uberspringen",
            "settings.intervals": "Intervalle",
            "settings.focus": "Fokus",
            "settings.break": "Pause",
            "settings.none": "keine",
            "settings.time.allMinutes": "Nur Minuten",
            "settings.time.withHours": "Mit Stunden",
            "settings.language": "Sprache",
            "performance.title": "Leistung",
            "performance.streak": "Serie %d T",
            "performance.today": "Heute",
            "performance.sessions": "Sitzungen",
            "performance.focus": "Fokus",
            "performance.tracked": "Getrackt",
            "history.day": "Tag",
            "history.pomodoros": "Pomodoros",
            "history.active": "Aktiv",
            "history.enableScroll": "Scrollen an",
            "history.disableScroll": "Scrollen aus",
            "activities.title": "Aktivitaten",
            "activities.new": "Neue Aktivitat",
            "activities.empty": "Noch keine Aktivitaten.",
            "activities.edit": "Bearbeiten",
            "activities.save": "Speichern",
            "activities.completed": "Erledigt",
            "activities.target": "Ziel",
            "activities.start": "Start",
            "activities.stop": "Stopp",
            "activities.interval.short": "Int.",
            "footer.history": "Verlauf wird lokal gespeichert.",
            "footer.quit": "Beenden",
            "track.noApps": "Keine Apps verfugbar",
            "track.stop": "Tracking stoppen",
            "away.30s": "30 Sekunden",
            "away.2m": "2 Minuten",
            "away.5m": "5 Minuten",
            "away.15m": "15 Minuten",
            "away.indefinite": "Unbegrenzt",
            "alert.focus.title": "Aktuelle Serie ist vorbei",
            "alert.focus.message": "Gut gemacht. Starte jetzt eine neue Fokus-Serie oder nimm deine konfigurierte Pause.",
            "alert.focus.startNew": "Neue Serie starten",
            "alert.focus.startBreak": "Pause starten",
            "alert.later": "Spater",
            "alert.activity.progress": "Aktivitatsfortschritt: %d/%d",
            "alert.activity.done": "Erledigt",
            "alert.activity.stopReminding": "Nicht mehr erinnern"
        ]
    ]
}
